name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Run `zig build`
        run: cd packages/core && zig build

      - name: Run `deno test`
        run: deno test -A

      - name: Install dependencies
        run: pnpm i

      - name: Build webcomponent
        run: cd packages/webcomponent && pnpm build
